matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: generic
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test
    - os: osx
      osx_image: xcode7.3
      language: objective-c
      xcode_project: SwiftCBOR.xcodeproj
      xcode_scheme: SwiftCBOR-Package
      install: echo ":)"
