matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      language: generic
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv install 4.1
      script: swift test
    - os: osx
      osx_image: xcode9.2
      language: objective-c
      install: echo ":)" # skip default (pods)
      script:
        - xcodebuild test -project SwiftCBOR.xcodeproj -scheme SwiftCBOR-Package -destination 'platform=OS X,arch=x86_64'
        - xcodebuild test -project SwiftCBOR.xcodeproj -scheme SwiftCBOR-Package -destination 'platform=Simulator,name=iPhone,OS=8.1'
