matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      language: generic
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv install 4.1 || swiftenv install 4.1 || swiftenv install 4.1
        # retry a few times, download should resume https://github.com/kylef/swiftenv/commit/33727158
      script: swift test
    - os: osx
      osx_image: xcode9.2
      language: objective-c
      install: echo ":)" # skip default (pods)
      script:
        - xcodebuild test -project SwiftCBOR.xcodeproj -scheme SwiftCBOR-Package -destination 'platform=OS X,arch=x86_64'
        - xcodebuild test -project SwiftCBOR.xcodeproj -scheme SwiftCBOR-Package -destination 'platform=iOS Simulator,name=iPhone X,OS=11.2'
